# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven to page

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 17 * * *"
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Person to greet"
        # Default value if no value is explicitly provided
        default: "0"
        # Input has to be provided for the workflow to run
        required: true
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          cache: maven
          java-version: 19
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Java Application
        run: java -jar target/bing-wallpaper-jar-with-dependencies.jar ${{ github.event.inputs.name }}
      - name: Commit files
        run: |
          git config --local user.email "8667302@gmail.com"
          git config --local user.name "8667302"
          git pull
          git add README.md
          git add bing-wallpaper.md
          git add bing-wallpaper.json
          git add picture/*
          date > docs/generated.txt
          git add docs/*
          git commit -m "update files by maven"
          git push origin main

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
